version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_SECRET_KEY=your-secret-key
    # env_file:
    #   - .env  # Add the env_file property here
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
